### ISSUE TITLE
"coercing to Unicode: need string or buffer, bool found" after 1 song finished in playlist

### ISSUE THREAD

**Issue by cgrozev** [jrnewell/spotify-ripper#108]
Hi. I cannot proceed past the first song in a playlist (in 2.5.2). This is the message I get:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 280, in run
    set_metadata_tags(args, self.audio_file, track)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/tags.py", line 50, in set_metadata_tags
    args.genres[0] + 's/' + uri_tokens[2])
TypeError: coercing to Unicode: need string or buffer, bool found

Any obvious error?

regards

Christo

**Comment by cgrozev** [comment]
It's obviously something in the genres parsing. I removed the genres and without it it is working fine.

**Comment by jrnewell** [comment]
The --genres options actually takes a parameter, ``--genres=artist`` or ``--genres=album``.

**Comment by cgrozev** [comment]
Thanks! That was it.
