### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by cgrozev** [jrnewell/spotify-ripper#112]
Hi. I am getting the following error when starting to work with (any) playlist:

    Loading playlist...
    Syncing playlist MOVIE Soundtracks & CINEMA Scores
    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
        self.run()
      File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 238, in run
        self.sync.sync_playlist(self.current_playlist)
       File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/sync.py", line 67, in sync_playlist
         if not os.path.exists(file_path):
       File "/usr/lib/python2.7/genericpath.py", line 18, in exists
         os.stat(path)
     UnicodeEncodeError: 'ascii' codec can't encode character u'\u015a' in position 61: ordinal not in           range(128)

What might the cause be?

Regards
Christo

**Comment by jrnewell** [comment]
I think I fixed this in ``2.6.0``, can you check?
