### ISSUE TITLE
KeyError: u'192'

### ISSUE THREAD

**Issue by welly** [jrnewell/spotify-ripper#114]
I've just installed spotify ripper in accordance to the install instructions but not having much luck in getting it working. When I try to rip a song, I get the following error

```
Spotify Ripper - v2.5.2
  Encoding output:	MP3, VBR 0
  Spotify bitrate:	192 kbps
  Unicode support:	ASCII only
  Output directory:	/Users/alastair
  Settings directory:	/Users/alastair/.spotify-ripper
  Format String:	{album_artist}/{album}/{artist} - {track_name}.{ext}
  Overwrite files:	No
Traceback (most recent call last):
  File "/usr/local/bin/spotify-ripper", line 9, in <module>
    load_entry_point('spotify-ripper==2.5.2', 'console_scripts', 'spotify-ripper')()
  File "/usr/local/bin/main.py", line 421, in main
    ripper = Ripper(args)
  File "/usr/local/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 111, in __init__
    self.session.preferred_bitrate(bit_rates[args.quality])
KeyError: u'192'
```

Not really sure where to start with this! Any help would be appreciated!

Thanks

**Comment by VikasRana** [comment]
try adding 320 bitrate ripping command. Yours is currently at 192. Let me know if it worked that way.

**Comment by welly** [comment]
Perfect, that sorted it! Thank you.
