### ISSUE TITLE
codecs str/bytes issue after upgrading to 2.5.2 from old version (+pip)

### ISSUE THREAD

**Issue by marianolatorre** [jrnewell/spotify-ripper#118]
I just performed an update of spotify ripper:

```
pip install --upgrade spotify-ripper
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting spotify-ripper
  Downloading spotify-ripper-2.5.2.tar.gz
Collecting pyspotify==2.0.3 (from spotify-ripper)
  Downloading pyspotify-2.0.3-cp34-cp34m-macosx_10_6_intel.whl (1.9MB)
    100% |████████████████████████████████| 1.9MB 151kB/s 
Requirement already up-to-date: colorama>=0.3.3 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from spotify-ripper)
Collecting mutagen==1.30 (from spotify-ripper)
  Downloading mutagen-1.30.tar.gz (890kB)
    100% |████████████████████████████████| 892kB 296kB/s 
Requirement already up-to-date: requests>=2.3.0 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from spotify-ripper)
Requirement already up-to-date: schedule>=0.3.1 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from spotify-ripper)
Collecting cffi>=1.0.0 (from pyspotify==2.0.3->spotify-ripper)
  Downloading cffi-1.2.1.tar.gz (335kB)
    100% |████████████████████████████████| 335kB 624kB/s 
Requirement already up-to-date: pycparser in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from cffi>=1.0.0->pyspotify==2.0.3->spotify-ripper)
Installing collected packages: cffi, pyspotify, mutagen, spotify-ripper
  Found existing installation: cffi 1.1.2
    Uninstalling cffi-1.1.2:
      Successfully uninstalled cffi-1.1.2
  Running setup.py install for cffi
  Found existing installation: pyspotify 2.0.0b4
    Uninstalling pyspotify-2.0.0b4:
      Successfully uninstalled pyspotify-2.0.0b4
  Found existing installation: mutagen 1.29
    Uninstalling mutagen-1.29:
      Successfully uninstalled mutagen-1.29
  Running setup.py install for mutagen
  Found existing installation: spotify-ripper 2.2.6
    Uninstalling spotify-ripper-2.2.6:
      Successfully uninstalled spotify-ripper-2.2.6
  Running setup.py install for spotify-ripper
Successfully installed cffi-1.2.1 mutagen-1.30 pyspotify-2.0.3 spotify-ripper-2.5.2
```

and pip:
```
pip install --upgrade pip
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pip
  Downloading pip-7.1.2-py2.py3-none-any.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 234kB/s 
Installing collected packages: pip
  Found existing installation: pip 7.1.0
    Uninstalling pip-7.1.0:
      Successfully uninstalled pip-7.1.0
Successfully installed pip-7.1.2
```

```
pip install --upgrade spotify-ripper
Requirement already up-to-date: spotify-ripper in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages
Requirement already up-to-date: pyspotify==2.0.3 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from spotify-ripper)
Requirement already up-to-date: colorama>=0.3.3 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from spotify-ripper)
Requirement already up-to-date: mutagen==1.30 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from spotify-ripper)
Requirement already up-to-date: requests>=2.3.0 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from spotify-ripper)
Requirement already up-to-date: schedule>=0.3.1 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from spotify-ripper)
Requirement already up-to-date: cffi>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from pyspotify==2.0.3->spotify-ripper)
Requirement already up-to-date: pycparser in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from cffi>=1.0.0->pyspotify==2.0.3->spotify-ripper)
```

But I started getting the following error, could you guys help me out? thanks

```
spotify-ripper -u mariano -p xxxx spotify:user:marianolatorre:playlist:13ifev244CKipI1fGetjZ2 --fail-log fail-songs.txt
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/spotify-ripper", line 9, in <module>
    load_entry_point('spotify-ripper==2.5.2', 'console_scripts', 'spotify-ripper')()
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/main.py", line 363, in main
    print(Fore.GREEN + "Spotify Ripper - v" + prog_version + Fore.RESET)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/codecs.py", line 374, in write
    self.stream.write(data)
TypeError: must be str, not bytes
```

**Comment by marianolatorre** [comment]
I sorted out this by :
- removing from PATH a folder pointing to framework 3.4, no idea how it got there...
- source .bash_profile (on mac os - mavericks)
- installing ports and both downloading and selecting python 2.7
- fresh install of pip and spotify-ripper

**Comment by jrnewell** [comment]
Yeah I kind of treat Python 3 as a second class citizen, but it seems to be working when I tested it last.
