### ISSUE TITLE
Fedora

### ISSUE THREAD

**Issue by theonewhoistwo** [jrnewell/spotify-ripper#127]
Hey, I really love this program. I ran it on my old machine with Ubuntu. on my new machine I need to run fedora and I couldn´t manage to install the ripper. There came a few errors when i used pip..
Do u have any idea on how to make it runon fedora?

**Comment by jrnewell** [comment]
I haven't used Fedora since the early 2000's, but I can give it a shot in a VM.  Can you log the error messages you see?

**Comment by theonewhoistwo** [comment]
When i type spotify-ripper -h

Traceback (most recent call last):
  File "/usr/bin/spotify-ripper", line 9, in <module>
    load_entry_point('spotify-ripper==2.6.2', 'console_scripts', 'spotify-ripper')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 558, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2682, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2355, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2361, in resolve
  File "/usr/bin/main.py", line 7, in <module>
    from spotify_ripper.ripper import Ripper
  File "/usr/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 9, in <module>
    from spotify_ripper.progress import Progress
  File "/usr/lib/python2.7/site-packages/spotify_ripper/progress.py", line 11, in <module>
    import spotify
  File "/usr/lib64/python2.7/site-packages/spotify/__init__.py", line 81, in <module>
    from spotify._spotify import ffi, lib  # noqa
ImportError: libspotify.so.12: cannot open shared object file: No such file or directory

I tried to reinstall it, same problem again.....

**Comment by jrnewell** [comment]
It looks like libspotify is not installed correctly...

pyspotify says you can do this (install from source):

libspotify is packaged in [rpmfusion non-free](http://rpmfusion.org/). Install the repository package, then run:
```
yum -y install libspotify-devel
```

**Comment by theonewhoistwo** [comment]
Awesome! Thanks for helping. By the way, on newer fedora systems it is:

sudo dnf install libspotify-devel. 

Anyway worked like a charm. :+1:
