### ISSUE TITLE
Ripping on Raspberry Pi 2

### ISSUE THREAD

**Issue by schteeben95** [jrnewell/spotify-ripper#129]
I'm trying to rip from Raspberry Pi 2, it can rip some files some time, but almost every time I try to rip a playlist, there is always a few files that will throw these errors:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper-2.6.2-py2.7.egg/spotify_ripper/ripper.py", line 287, in run
    self.finish_rip(track)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper-2.6.2-py2.7.egg/spotify_ripper/ripper.py", line 787, in finish_rip
    self.pipe.close()
IOError: close() called during concurrent operation on the same file object.
```

**Comment by jrnewell** [comment]
Can you give it a shot on version ``2.6.3``?

**Comment by schteeben95** [comment]
Yes! Thank you! Building from GitHub instead of getting easy_install solved it for me :) Thank you!
