### ISSUE TITLE
Incompatibility with vowels mutations (ü,ö,ä)

### ISSUE THREAD

**Issue by Hendrik410** [jrnewell/spotify-ripper#137]
When I try to rip a song with an mutation in the title it says:

```
Loading album browser...
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py",
 299, in run
    self.progress.calc_total(all_tracks)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/progress.py
ne 66, in calc_total
    if not self.args.overwrite and os.path.exists(audio_file):
  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in posit
8: ordinal not in range(128)
```

Aperantly it only supports ascii and has a problem if the value exceeds 128.

Is there a easy way to fix it?

**Comment by jrnewell** [comment]
There is the ``--ascii`` tag if your terminal doesn't support unicode.  I read somewhere that setting this environment variable could help: ``export PYTHONIOENCODING=utf-8``.

**Comment by jrnewell** [comment]
Can you try ``2.6.9``... i think this should be fixed.
