### ISSUE TITLE
Exception in thread SpotifyRipperThread: ValueError: Failed to get link from Spotify URI: 'uri'

### ISSUE THREAD

**Issue by cc46808** [jrnewell/spotify-ripper#139]
I get this error, any suggestions?

`Exception in thread SpotifyRipperThread:`

```
spotify-ripper --aac -l uri spotify:track:0jh2HyqarexLFrEyN1dpKp
Spotify Ripper - v2.6.8
  Encoding output:	AAC, VBR 500
  Spotify bitrate:	320 kbps
  Unicode support:	Yes
  Output directory:	/Users/Business
  Settings directory:	/Users/Business/.spotify-ripper
  Format String:	{album_artist}/{album}/{artist} - {track_name}.{ext}
  Overwrite files:	No
Logging in...
Logged in as #######
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Python/2.7/site-packages/spotify_ripper/ripper.py", line 193, in run
    tracks = get_tracks_from_uri(uri)
  File "/Library/Python/2.7/site-packages/spotify_ripper/ripper.py", line 188, in get_tracks_from_uri
    return self.load_link(uri)
  File "/Library/Python/2.7/site-packages/spotify_ripper/ripper.py", line 312, in load_link
    link = self.session.get_link(uri)
  File "/Library/Python/2.7/site-packages/spotify/session.py", line 376, in get_link
    return spotify.Link(self, uri=uri)
  File "/Library/Python/2.7/site-packages/spotify/link.py", line 73, in __init__
    'Failed to get link from Spotify URI: %r' % uri)
ValueError: Failed to get link from Spotify URI: 'uri'
```

**Comment by jrnewell** [comment]
Yeah, just remove the word 'uri' - you don't need to include that in the argument list.

**Comment by cc46808** [comment]
ha thanks! Now I feel like an idiot!

**Comment by jrnewell** [comment]
It is no problem :smiley:
