### ISSUE TITLE
--remove-from-playlist error

### ISSUE THREAD

**Issue by thisisflorian** [jrnewell/spotify-ripper#144]
I get an error when I try to download a playlist with the parameter -r.
I am using version 2.6.9 installed on Raspberry Pi B (1st generation).

The playlist will get downloaded and when finished, i get the following error:
```
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 302, in run
    self.post.remove_tracks_from_playlist()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/post_actions.py", line 188, in remove_tracks_from_playlist
    ripper.current_playlist and len(ripper.tracks_to_remove) > 0:
AttributeError: 'Ripper' object has no attribute 'tracks_to_remove'
```

Here is my config.ini:
```
[main]
format = {album_artist}/{album}/{track_num:2} {track_name}.{ext}
bitrate = VBR
directory = Music
user = myusername
password = password
```

Here is my commandline:
```
spotify-ripper -r spotify:user:myusername:playlist:1lHtHmOmBn83kGnRtPjn7O
```

**Comment by jrnewell** [comment]
Good catch... fixed in ``2.6.10``.
