### ISSUE TITLE
Unable to export Playlist

### ISSUE THREAD

**Issue by gthayer** [jrnewell/spotify-ripper#154]
I am able to export individual songs but not playlists when using the format described in the documentation. Example:

```
$ spotify-ripper -l spotify:user:username:playlist:0Kp1bausKk2MKPvKoyACup
```

```
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 197, in run
    tracks = get_tracks_from_uri(uri)
  File "/usr/local/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 192, in get_tracks_from_uri
    return self.load_link(uri)
  File "/usr/local/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 327, in load_link
    self.current_playlist.load()
AttributeError: 'NoneType' object has no attribute 'load'
```

**Comment by gthayer** [comment]
I figured it out. I'm a dummy.

The 'username' section of the request string needs my user ID number. This can be found when copying the playlist URI.

Closing ticket.
