### ISSUE TITLE
'NoneType' object has no attribute 'load'

### ISSUE THREAD

**Issue by MasterSmollett** [jrnewell/spotify-ripper#158]
Loading playlist...
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/Users/toby/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/toby/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 214, in run
    tracks = list(get_tracks_from_uri(uri))
  File "/Users/toby/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 194, in get_tracks_from_uri
    return self.load_link(uri)
  File "/Users/toby/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 361, in load_link
    self.current_playlist.load()
AttributeError: 'NoneType' object has no attribute 'load'

**Comment by ellipticaldoor** [comment]
+1

**Comment by jrnewell** [comment]
I am having trouble replicated this and don't see anything obviously buggy in that function... do you have more information on your configuration, platform and arguments that are using.  Do you see it reliably on every run or on every URI or just randomly?

**Comment by MasterSmollett** [comment]
Running on OS X El Capitain. Happens every time. Don't know what other information I can give, but thanks for your time.

**Comment by jrnewell** [comment]
Hmm I am using el cap too ... do you have a spotify URI I can test with?  It almost it looks it is a playlist that spotify doesn't want to give you access to and returning None, but what is weird is that it calls ``get_tracks_from_uri`` on line 199 fine according to your trace.  I wonder if it is just a temp blip with loading playlists and I could have it just retry a few times on failure.

**Comment by MasterSmollett** [comment]
This is one of the playlists i tried... https://open.spotify.com/user/ivanushki.international/playlist/18PoyHEvFmcVvRNWWK4Qyh

**Comment by elmolinger** [comment]
same here

```
spotify:user:username:playlist:1Bu07dOrDh9U7Zjf4ALrrV

Loading playlist...
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 199, in run
    tracks = get_tracks_from_uri(uri)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 194, in get_tracks_from_uri
    return self.load_link(uri)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 361, in load_link
    self.current_playlist.load()
AttributeError: 'NoneType' object has no attribute 'load'
```
ripping a single Songs works fine for me.

**Comment by jrnewell** [comment]
Ok, in ``2.7.1``, I tried to handle when Spotify returns ``None`` for the playlist better.  It will pause and try retrieving the playlist two additional times before skipping.  Let me know if that helps. If that is the case, then failure was due to a transient issue with Spotify.  If it doesn't, that means it is something else that changed...

**Comment by MasterSmollett** [comment]
OK thanks! I'll give it a try...

**Comment by MasterSmollett** [comment]
Nope no progress 
```
Could not load playlist...
```
