### ISSUE TITLE
ascii codec can't encode character

### ISSUE THREAD

**Issue by WebDesZ** [jrnewell/spotify-ripper#16]
I get the following error - also with the "-a" flag. How to fix that?

[code]
Ripping spotify:track:4jX1652KDDDGX286Li7QqF
/***/John Dahlbck/Stage Door - A House Entry/John Dahlbck - Hustle Up - Albin Myers Remix.mp3
Progress: [======================================= ] 7:36 / 7:40
Rip complete
John Dahlbck - Hustle Up - Albin Myers Remix.mp3	[ 14.97 MB ]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 147, in run
    set_id3_and_cover(args, self.mp3_file, track)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/id3.py", line 77, in set_id3_and_cover
    print(Fore.YELLOW + "Setting artist: " + track.artists[0].name + Fore.RESET)
  File "/usr/local/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 36, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 133, in write
    self.write_and_convert(text)
  File "/usr/local/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 158, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "/usr/local/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 166, in write_plain_text
    self.wrapped.write(text[start:end])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 26: ordinal not in range(128)
[/code]

**Comment by jrnewell** [comment]
Good catch.  Fixed in ``1.1.3`` or 51b17b7.

**Comment by WebDesZ** [comment]
Track: Major Lazer - Lean On (feat. MØ & DJ Snake).mp3
spotify:track:0BF6mdNROWgYo3O3mNGrBc

(Without the "-a" flag)

> /usr/local/bin/spotify-ripper -V
1.1.3

>>>>>
Skipping spotify:track:0BF6mdNROWgYo3O3mNGrBc
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 131, in run
    print(Fore.CYAN + self.mp3_file + Fore.RESET)
  File "/usr/local/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 36, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 133, in write
    self.write_and_convert(text)
  File "/usr/local/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 158, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "/usr/local/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 166, in write_plain_text
    self.wrapped.write(text[start:end])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd8' in position 53: ordinal not in range(128)
<<<<<

**Comment by jrnewell** [comment]
which platform are you running on?

**Comment by WebDesZ** [comment]
Raspberry PI B - Raspbian
Linux zpi 3.18.11+ #781 PREEMPT Tue Apr 21 18:02:18 BST 2015 armv6l GNU/Linux

**Comment by jrnewell** [comment]
It looks like your terminal setup with raspian doesn't support unicode characters?  If not you, you should use the ``-a`` option with version ``1.1.3``, or you could play around with your terminal or locale settings.
