### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by spravo13** [jrnewell/spotify-ripper#166]
I am having this error:

 `Traceback (most recent call last):
  File "/usr/local/bin/spotify-ripper", line 9, in <module>
    load_entry_point('spotify-ripper==2.6.4', 'console_scripts', 'spotify-ripper')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2697, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2370, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2376, in resolve
  File "/usr/local/bin/main.py", line 7, in <module>
    from spotify_ripper.ripper import Ripper
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 8, in <module>
    from spotify_ripper.tags import set_metadata_tags
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/tags.py", line 11, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 68, in <module>
    error=-1)
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 57, in wrapper
    ffi.def_extern(name=name, **kwargs)(func)
AttributeError: 'CompiledFFI' object has no attribute 'def_extern'
`

I have never had a problem with this application before. Any advice? 

Thanks!

**Comment by jrnewell** [comment]
From what I read from someone who had a similar issue (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813597), you just have a mismatch on your pip installed cffi package vs dpkg -l python-cffi.  Does upgrading your cffi package help?
```shell
pip install --upgrade cffi
```

**Comment by spravo13** [comment]
I get a similar error when trying to upgrade cffi:

`root: ~ ✗ # pip install --upgrade cffi
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2697, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2370, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2376, in resolve
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 22, in <module>
    import requests, six
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 68, in <module>
    error=-1)
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 57, in wrapper
    ffi.def_extern(name=name, **kwargs)(func)
AttributeError: 'CompiledFFI' object has no attribute 'def_extern'
`

I am considering just rebuilding pip from source to see if it hammers out the errors but if you have a different suggestion, I would love to hear it. 

Thank you!

**Comment by jrnewell** [comment]
Did you ever resolve this?

**Comment by spravo13** [comment]
I never did end up fixing it on my desktop. In the string of things I did to try to fix it I completely purged python, without regards to what it may break... After fixing basically my whole setup and reconfiguring everything, I tried to setup this application again with no success,

No worries though, pulled out the old laptop with Kali on it, installed the pre-requisites, installed this and was back in buisness. 

Thanks anyway!

**Comment by growing** [comment]
This fixed it for me;

sudo rm -rf /usr/lib/python2.7/dist-packages/cryptography
pip install cryptography

**Comment by spravo13** [comment]
I tried what @growing suggested and am now recieving a different error:

```
Traceback (most recent call last):
  File "/usr/local/bin/spotify-ripper", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3095, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3081, in _call_aside
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 658, in _build_master
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 959, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 846, in resolve
pkg_resources.DistributionNotFound: The 'requests>=2.3.0' distribution was not found and is required by spotify-ripper
```

Again, am not using my main machine for this anymore since I was able to get the program to work on a separate box, but figured other people may be having this problem and it should be resolved.
