### ISSUE TITLE
can't concat bytes to sting

### ISSUE THREAD

**Issue by rolandg** [jrnewell/spotify-ripper#173]
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/site-packages/spotify_ripper-2.7.4-py3.5.egg/spotify_ripper/ripper.py", line 235, in run
    self.sync.sync_playlist(self.current_playlist)
  File "/usr/lib/python3.5/site-packages/spotify_ripper-2.7.4-py3.5.egg/spotify_ripper/sync.py", line 62, in sync_playlist
    lib = self.load_sync_library(playlist)
  File "/usr/lib/python3.5/site-packages/spotify_ripper-2.7.4-py3.5.egg/spotify_ripper/sync.py", line 51, in load_sync_library
    lib_path = self.sync_lib_path(playlist)
  File "/usr/lib/python3.5/site-packages/spotify_ripper-2.7.4-py3.5.egg/spotify_ripper/sync.py", line 37, in sync_lib_path
    return os.path.join(lib_path, uri_tokens[4].encode(encoding) + ".json")
TypeError: can't concat bytes to str

[1]    11778 segmentation fault (core dumped)  spotify-ripper spotify:user:mackmesser:playlist:184PA0eEFjtsc5yKobUPhU 

i suggest changing uri_tokens[4].encode(encoding) to uri_tokens[4] 
cheers

EDIT:
ok there is some other problem.. after removed the .encoding() tags in line 37 and 72 i get this

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/site-packages/spotify_ripper-2.7.4-py3.5.egg/spotify_ripper/ripper.py", line 235, in run
    self.sync.sync_playlist(self.current_playlist)
  File "/usr/lib/python3.5/site-packages/spotify_ripper-2.7.4-py3.5.egg/spotify_ripper/sync.py", line 68, in sync_playlist
    for uri, file_path in lib.items():
RuntimeError: dictionary changed size during iteration

options:
[main]
ascii = True
format = {idx}_{artist}-{track_name}.{ext}
quality = 320

and --playlist-sync

**Comment by jrnewell** [comment]
Yeah, that was definitely a bug on my end.  I checked in a fix and will make a new release soon... good catch!

**Comment by jrnewell** [comment]
Should be fixed in version ``2.7.5``.

**Comment by rolandg** [comment]
cheers..
