### ISSUE TITLE
TypeError when ripping tracks (playlists ok)

### ISSUE THREAD

**Issue by ajoh99** [jrnewell/spotify-ripper#176]
I am getting a type error when I rip tracks or albums. The app crashes when writing data / cover into the file at the end. 

I think it is failing to get the playlist name and crashing - which sort of makes sense as these are not in a playlist. However, I would assume it would just get playlist name as empty and not crash out. It is same with anscii mode or not, and any type of transcode target.

However, when I rip a playlist I have made, it downloads perfect and works as expected including correct data inside the files and integrated album covers.

Anyone else having this issue?

Config: [main]
format = {album_artist}/{album}/{artist} - {track_name}.{ext}
quality = 320
mp4 = true
last = True

-------------------------------------------------------------------------------
Writing Apple iTunes metadata - mp4a.40.2
-------------------------------------------------------------------------------
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/home/aj/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/aj/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 317, in run
    self.post.create_playlist_m3u(tracks)
  File "/home/aj/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/post_actions.py", line 103, in create_playlist_m3u
    name = sanitize_playlist_name(to_ascii(self.get_playlist_name()))
  File "/home/aj/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/utils.py", line 53, in sanitize_playlist_name
    return re.sub(r"[\\/]", "-", name)
  File "/home/aj/.pyenv/versions/2.7.10/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Comment by LanchaBasualdo** [comment]
same error here

**Comment by jrnewell** [comment]
Yeah sorry, there was a regression in the previous release.  Should be fixed in ``2.7.6``.
