### ISSUE TITLE
How to write files of URIs

### ISSUE THREAD

**Issue by noAlvaro** [jrnewell/spotify-ripper#18]
It is told that we can use a *file of URIs* as the positional URI argument.
- Question is: how would that file look like? It is an txt? And what's inside?

Thanks!

**Comment by jrnewell** [comment]
Hi noAlvaro,

Yes, you can pass the name of a file instead of a spotify uri.  The file is just a basic text file with a list of URIs - one URI per line.  For example:

```text
spotify:track:51AjDFaNRMWIOkn9PNCcpQ
spotify:track:7mocbWQc7a3Y7AOZNUpRJC
spotify:track:4WbJfIsqn6Zfn2OCT4aacB
```

It will just rip those URIs one after the other.  I will try to update the README to make this more clear.

**Comment by noAlvaro** [comment]
Nice. Thanks!

**Comment by noAlvaro** [comment]
This script seems to be halting due to timeout, when dealing with a larger number of URIs.

Look at the output:

```bash
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Python/2.7/site-packages/spotify_ripper/ripper.py", line 109, in run
    tracks = itertools.chain(*[self.load_link(line.strip()) for line in open(args.uri)])
  File "/Library/Python/2.7/site-packages/spotify_ripper/ripper.py", line 205, in load_link
    album_browser.load()
  File "/Library/Python/2.7/site-packages/spotify/album.py", line 262, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/Library/Python/2.7/site-packages/spotify/utils.py", line 240, in load
    raise spotify.Timeout(timeout)
Timeout: Operation did not complete in 10.000s
```

**Comment by jrnewell** [comment]
Do you which spotify URI link it timed-out on?  There was a similar to defect where someone was having similar issues with spotify timing out on loading a album.

**Comment by noAlvaro** [comment]
It varies, at least I saw it happening with different albums. But new attempts of loading the same URI file after a first crash will eventually solve this issue. It's strange.

**Comment by 14granville** [comment]
I've encountered the same problem.
