### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by LeonidasFox** [jrnewell/spotify-ripper#183]
```
nol2@nol2-VirtualBox:~$ spotify-ripper -u nol.1995 --playlist-sync spotify:user:<username>:playlist:0C8eMpoC2yBF8YGkLO8>>
Spotify Ripper - v2.8.2
  Encoding output:	MP3, VBR 0
  Spotify bitrate:	320 kbps
  Unicode support:	Yes
  Output directory:	/media/sf_Share2/Spotirip/music
  Settings directory:	/home/nol2/.spotify-ripper
  Format String:	{playlist}/{album_artists_web}/{album}/{idx:3}{track_num}{track_artists}{feat_artists:feat.} - {track_name}
  Overwrite files:	No
Traceback (most recent call last):
  File "/usr/local/bin/spotify-ripper", line 9, in <module>
    load_entry_point('spotify-ripper==2.8.2', 'console_scripts', 'spotify-ripper')()
  File "/usr/local/bin/main.py", line 474, in main
    ripper = Ripper(args)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 86, in __init__
    self.post = PostActions(args, self)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/post_actions.py", line 31, in __init__
    _base_dir, args.fail_log[0]), 'w', encoding)
  File "/usr/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'bool' object has no attribute 'startswith'

```

**Comment by jrnewell** [comment]
What do you have in your config.ini file?  Specifically, the ``fail-log`` option.

**Comment by LeonidasFox** [comment]
I've activated the fail-log option. I'll post the full config.ini in the
evening.
Am 08.03.2016 02:19 schrieb "James Newell" <notifications@github.com>:

**Comment by jrnewell** [comment]
Just curious, are setting "True" to that option or passing in a file name.... it actually takes a filename.

**Comment by LeonidasFox** [comment]
Thanks. 
It was set to True rather than to a file name.
