### ISSUE TITLE
Can't rip from charts

### ISSUE THREAD

**Issue by tungmeister** [jrnewell/spotify-ripper#188]
when trying to rip a chart the following error is produced
`Attempting to retrieve gb regional charts from Spotify's Web API
https://spotifycharts.com/api/?limit=200&country=gb&recurrence=daily&date=latest&type=regional
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Python/2.7/site-packages/spotify_ripper/ripper.py", line 218, in run
    tracks = get_tracks_from_uri(uri)
  File "/Library/Python/2.7/site-packages/spotify_ripper/ripper.py", line 206, in get_tracks_from_uri
    chart_uris = [t["track"]["uri"] for t in charts["entries"]["items"]]
KeyError: u'uri'`

**Comment by animatenate** [comment]
Same error here... anybody have a fix for this? Everything else has been working great for me. Thanks soo much for putting this project together!:)

Attempting to retrieve global regional charts from Spotify's Web API
https://spotifycharts.com/api/?limit=200&country=global&recurrence=weekly&date=latest&type=regional
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/Users/Tim/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/Tim/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 218, in run
    tracks = get_tracks_from_uri(uri)
  File "/Users/Tim/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 206, in get_tracks_from_uri
    chart_uris = [t["track"]["uri"] for t in charts["entries"]["items"]]
KeyError: u'uri'

**Comment by jrnewell** [comment]
Can you try again on version ``2.8.4``?

**Comment by animatenate** [comment]
upgrading to 2.8.4 fixed this for me. Thanks @jrnewell 


@tungmeister I had to upgrade my pip version from 6.1.1 to 8.1.1 as well>>>
$ pip install --upgrade pip

then upgrade spotify-ripper>>>
$ pip install --upgrade spotify-ripper

**Comment by egeu5** [comment]
Same issue here. I am using 

`spotify-ripper -V
2.9.1
`
