### ISSUE TITLE
Settings in config.ini file

### ISSUE THREAD

**Issue by acorven** [jrnewell/spotify-ripper#195]
There are settings that not apply, for example, playlist, id3-v23, d, stereo-mode,...

[main]
format = ({year}) {album_artist} - {album}/{artist} - {track_num:2} - {track_name}.{ext}
quality = 320
cbr = True
last = True
stereo-mode = s
id3-v23 = True
playlist-m3u = True
d = ~/acd

Thanks.

**Comment by hansmueller100000** [comment]
Same here, at least 

"playlist-m3u = True"
and
"playlist-sync = True"

seems to be ignored in the settings file.
(It's not that much to add it to the command though.. :D)

**Comment by jrnewell** [comment]
I think I added a fix for this in 2.8.6, can you check?

**Comment by acorven** [comment]
destination (d) setting does not work yet... 

remove cache setiing neither... 

Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/spotify_ripper/ripper.py", line 349, in run
    self.post.remove_offline_cache()
  File "/usr/local/lib/python3.4/dist-packages/spotify_ripper/post_actions.py", line 286, in remove_offline_cache
    "Storage")
  File "/usr/lib/python3.4/posixpath.py", line 89, in join
    "components") from None
TypeError: Can't mix strings and bytes in path components

Segmentation fault (core dumped) --> This is another error that I pointed in #109

**Comment by acorven** [comment]
D option works with "directory". Ok.

**Comment by jrnewell** [comment]
I think this is fixed in ``2.8.9``
