### ISSUE TITLE
Spotify error detected 'ascii' codec can't encode character u'\xd8' in position 63: ordinal not in range(128)

### ISSUE THREAD

**Issue by wallee9000** [jrnewell/spotify-ripper#202]
Hi,

Im using V2.8.4 and encounter sometimes the following problem:
Can i solve this by using --ascii option?

--
Spotify error detected
'ascii' codec can't encode character u'\xd8' in position 63: ordinal not in range(128)
Skipping to next track...
Deleting partially ripped file
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 331, in run
    self.post.clean_up_partial()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/post_actions.py", line 238, in clean_up_partial
    rm_file(ripper.audio_file)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/utils.py", line 95, in rm_file
    os.remove(file_name)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd8' in position 63: ordinal not in range(128)
--

Thanks,

**Comment by wallee9000** [comment]
Sorry, i just read the wiki and i will try first

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

Next time i read more first :)
Thanks
