### ISSUE TITLE
Specifying 'use last credentials' when none stored causes crash

### ISSUE THREAD

**Issue by dylanjboyd** [jrnewell/spotify-ripper#21]
When performing a rip and specifying the '-l' option for **using previous credentials when none exist**, the ripper crashes, as below:

```
$ spotify-ripper -l spotify:album:5NcC2WQ4sMn8qy2fTqdcWb
Logging in...
No credentials stored
Loading album browser...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Python/2.7/site-packages/spotify_ripper/ripper.py", line 108, in run
    tracks = self.load_link(args.uri)
  File "/Library/Python/2.7/site-packages/spotify_ripper/ripper.py", line 202, in load_link
    album_browser.load()
  File "/Library/Python/2.7/site-packages/spotify/album.py", line 262, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/Library/Python/2.7/site-packages/spotify/utils.py", line 228, in load
    % session.connection.state)
RuntimeError: Session must be logged in and online to load objects: <ConnectionState.LOGGED_OUT: 0>
```

An error message in place of this `RuntimeError` would be simply splendid.

**Comment by jrnewell** [comment]
I committed a fix for this in 2b391c6 / version ```1.2.1``.
