### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by wessel145** [jrnewell/spotify-ripper#210]
Hey, Since a few days i'm getting the following error:

Logging in...
Logged in as ******
Loading playlist...
Loading playlist...
Loading playlist...
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 232, in run
    if track.availability == 1 else None
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 590, in format_track_path
    format_track_string(self, args.format[0].strip(), idx, track)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/utils.py", line 175, in format_track_string
    album_browser.load()
  File "/usr/local/lib/python2.7/dist-packages/pyspotify-2.0.5-py2.7-linux-armv7l.egg/spotify/album.py", line 264, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyspotify-2.0.5-py2.7-linux-armv7l.egg/spotify/utils.py", line 246, in load
    raise spotify.Timeout(timeout)
Timeout: Operation did not complete in 10.000s`

**Comment by garis** [comment]
In the last 2 months it happens a lot of time also to me.
Try again and again and it will eventually work.

**Comment by wessel145** [comment]
I am trying again for a day now. still none of the attempts worked..

**Comment by smk** [comment]
Just updated from 2.8.3 to 2.8.9 and started to see only timeouts. Reverting back to 2.8.3 and it works again, so there must have been a faulty change somewhere in between.

**Comment by smk** [comment]
Commit 7219d916d266af78187c2de31d1df4665d82d2c4 from #200 added the offending call to `album_browser.load()` to `format_track_string`

**Comment by wessel145** [comment]
@jrnewell Still no fix for this? i'd like to use the newest version, but it's not working

**Comment by seandex** [comment]
I found out why this happens and freaked me out for almost a month.

1. timeout error caused if you are on VPS (especially OpenVZ or XEN and hosts with overselling resources). it will work low percentage chance when the server resources are not busy. it might worked flawlessly before but now the server your on is FULL. 
    1) if you change the plan to KVM(like OpenStack) it is guaranteed resource and most of ripping will be done in 1 minute and 30 seconds per song.
    2) VPS with SSD helps a little bit but the resources are over sold, you need to look for hosting with KVM.

2. If you are not on VPS, then, having VPN setup will also delay the ripping and gives you timeout error. this happened on my MB PRO, I could not find the reason why but turning off the VPN works like charm! I re-enabled VPN guess what? timeout error from the first song, I disabled again to MAKE SURE it is VPN, it works again!

I hope this helps.. and I do not blame on new versions now because I found out they work great. they are either better versions and more likely have less bugs and works clearer than old versions. I'm on the latest versions and don't have any issues. 

oh one more thing, if this one helps again, 

this is how i installed the ripper from scratch.. (and installed only what it required)
on fresh installed debian jessie and python 2.7.9(which is built in basic) 
*no pyenv, 
*no pip headaches

1) sudo apt-get update 
2) wget https://github.com/jrnewell/spotify-ripper/archive/master.zip
    ---  unzip then go to directory.... 
2) python setup.py build
3) sudo python setup.py install (i get an requirement package errors, but i fix it in the following lines)
4) sudo apt-get install python-setuptools (i kept on responded to the minor error msgs because i didn't want to install unnecessary packages)
5) wget -q -O - https://apt.mopidy.com/mopidy.gpg | sudo apt-key add -
6) sudo wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/jessie.list
7) sudo apt-get update
8) sudo apt-get install python-spotify
9) sudo apt-get install flac
10) sudo apt-get install lame

now it works great on my KVM vps and macbook pro!

i also thank you hover20 for the unzip method!

**Comment by asoretmadolell** [comment]
I've also been having that exact same error when ripping a playlist, and tried what you did, but didn't work for me (I'm running Ubuntu on a Hyper-V host). I retried for several days straight without any luck. Then it ocurred to me... What if the problem is Spotify's and not ours? I had seen it return errors a few times before, like not finding songs that were intentionally deleted (which makes no sense), so it seemed probable. What I did was, just to try, create a new playlist, add the songs from my previous playlist to the new one, and try to rip the new playlist. I've had no problems ever since :smile: . However, would it be nice to have an option to increase the 10 second timeout wait? I wonder if that's of any use on some particular scenarios.

**Comment by seandex** [comment]
what's the average time estimate per 1 song? i would still say resource problems if it goes more than 2 minutes or almost same time as song which is 4mins to 5mins..
mines now only has 1mins and 10 secs after problem goes away..
oh.. also try to re-download any playlist again.. i too sometimes fully ripped a playlist and then next failed again.. i would rather move the host with guaranteed resource and stay peace of mind :)

**Comment by dorneanu** [comment]
Hi! I have the same timeout issue when trying to rip a playlist with lots of tracks (>50). On my system (arch linux) in `/usr/lib/python2.7/site-packages/spotify/utils.py` there is `load()`:

```
def load(session, obj, timeout=None):
....
if timeout is None:
  timeout = 10
...
```

Changing the timeout to sth else (by editing the file manually) solves the problem. However `spotify-ripper` should call `load()` with `timeout` set properly (any chance to get that in `~/.spotify-ripper/config.ini`?). 

Cheers,
Victor

**Comment by orcomma** [comment]
Hi!! Novice here!! 

I am running on Windows 10 Anniversary Ubuntu Linux Bash - following the instructions for installation the ripper works fine but with big playlists I get the above timeout error too.  

Whereabouts is the file to change the timeout value as per the above post?  I can find the `/usr/lib/python2.7/ folder` but not the `site-packages` subfolder within it...?

**Comment by fewerflatlands** [comment]
this is happening to me relentlessly, both with playlists and individual tracks
example trace:
```Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/Users/as/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/as/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 233, in run
    audio_file = self.format_track_path(idx, track)
  File "/Users/as/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 609, in format_track_path
    track.load()
  File "/Users/as/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify/track.py", line 81, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/Users/as/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify/utils.py", line 246, in load
    raise spotify.Timeout(timeout)
Timeout: Operation did not complete in 10.000s
```

**Comment by jrnewell** [comment]
ok, i added a ``--timeout`` option to override the timeout value in version ``2.10.5``.

**Comment by fewerflatlands** [comment]
@jrnewell super, much appreciated.

**Comment by orcomma** [comment]
@jrnewell yeah, fab, thank you!

**Comment by dorneanu** [comment]
Great! Thx!

**Comment by asoretmadolell** [comment]
Thank you! :smile:
