### ISSUE TITLE
Symbol not found: _PyUnicodeUCS2_AsASCIIString

### ISSUE THREAD

**Issue by hover20** [jrnewell/spotify-ripper#214]
Hello everybody,

Operating-System: OSX 10.11.4 (15E65)
Python: Python 2.7.10 (default, May  2 2016, 14:06:20) 

I'm trying to update my current spotify-ripper (2.8.2) to the latest release (pip install spotify-ripper).

After a good-looking installation I executed the command "spotify-ripper -V" and the following error appeared:

I think the error is: "Symbol not found: _PyUnicodeUCS2_AsASCIIString" -> See traceback

I'm already tried to follow the steps in issue #162 but this doesn't work for me.

->

pyenv uninstall 2.7.10
export CONFIGURE_OPTS="--enable-unicode=ucs4"
pyenv install 2.7.10
pip install --upgrade pip
pip install spotify-ripper

--------------------------------------------------------------------

spotify-ripper -V
Traceback (most recent call last):
  File "/Users/Flo/.pyenv/versions/2.7.10/bin/spotify-ripper", line 9, in <module>
    load_entry_point('spotify-ripper==2.8.9', 'console_scripts', 'spotify-ripper')()
  File "/Users/Flo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/Flo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "/Users/Flo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2345, in load
    return self.resolve()
  File "/Users/Flo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/Flo/.pyenv/versions/2.7.10/bin/main.py", line 7, in <module>
    from spotify_ripper.ripper import Ripper
  File "/Users/Flo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 9, in <module>
    from spotify_ripper.progress import Progress
  File "/Users/Flo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/progress.py", line 11, in <module>
    import spotify
  File "/Users/Flo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify/__init__.py", line 81, in <module>
    from spotify._spotify import ffi, lib  # noqa
ImportError: dlopen(/Users/Flo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_cffi_backend.so, 2): Symbol not found: _PyUnicodeUCS2_AsASCIIString
  Referenced from: /Users/Flo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_cffi_backend.so
  Expected in: flat namespace
 in /Users/Flo/.pyenv/versions/2.7.10/lib/python2.7/site-packages/_cffi_backend.so
 
 
 --------------------------------------------------------------------

Thanks a lot!

**Comment by jrnewell** [comment]
For some reason, your error message is saying the opposite of issue #162.  Try the instructions again, but instead do
```
export CONFIGURE_OPTS="--enable-unicode=ucs2"
```

That being said, it seems like you are using some libspotify/pyspotify version that was compiled for 2-byte unicode, which doesn't seem right to me.

**Comment by jstiers** [comment]
I have a very similar error, but I've tried `export CONFIGURE_OPTS="--enable-unicode=ucs2"` as well as `export CONFIGURE_OPTS="--enable-unicode=ucs4"
`
Nothing works. Am I doomed?

**Comment by hover20** [comment]
Hello everybody,

I think I found a solution for this error on OSX.

1. Remove your spotify-ripper installation (brew uninstall spotify-ripper). If you installed via the setup.py you have to remove it manually. You will find the path by typing "type -a spotify-ripper" in terminal.

2. Reinstall the spotify-ripper by downloading version 2.8.3 up to 2.8.7 -> Step-by-Step! I installed 2.8.3, then 2.8.4 then 2.8.5, an so on. (Yes, may you can skip versions).

I think the error occurred at version 2.8.8 so I only upgraded up to 2.8.7 :) This is a good temporarily solution but it has to fix.

How to install by downloading the zip?

- Download the zip
- Go to terminal
- type "python setup.py build"
- type "python setup.py install"
- Ready to play :)

I will test other solution but not at the moment. You can also try to install lower versions with brew if you specify your target version "pip install spotify-ripper==2.8.3"

**Comment by jstiers** [comment]
I still can't get it to work. But thank you for your time effort in putting this guide together "hover20"!

I think I'll have to use a VMware or something and try it there. Dunno what's wrong with my mac :(.

**Comment by hover20** [comment]
This is another workaround, not really a solution :P You can use the Vagrantfile. Don't know Vagrant? Vagrant is an provisining tool to create virtual machine automatically by a single user command. This project includes a vagrant file. 

So what to do?

- Install Virtual Box -> https://www.virtualbox.org/wiki/Downloads
- Install Vagrant (The provisioning tool) -> https://www.vagrantup.com
- Open the Terminal an change to your spotify-ripper GUI directory, downloaded from GitHub
- Run the command "vagrant up"

-> Vagrant will set up an Ubuntu 64 bit Virtual Machine (automatically download a smallsize image of the latest Ubuntu version) and also automatically installs spotify-ripper for you.
-> After successful setup type "ssh". You are now connected to your vm and able to use spotify-ripper

If you open your native virtual box application you will see the recently created virtual box :)

For further questions, please ask :) 

-> @jrnewell  May you should add a shared folder for 
1. Easy way to copy the spotify developer key to the vm 
2. and copy downloaded tracks to your host

May I edit your file today or tomorrow and send you my proposal :)

**Comment by jstiers** [comment]
Thanks for all the work you're putting in.
But maybe I'm just not supposed to get music from Spotify lol.

Can't start the Virtualbox.
I just typed `vagrant ssh` and everything seems to work, but then in Virtualbox it can't run the VM.

**Comment by hover20** [comment]
Hm ssh is not activated. I will extend the configuratuon file and upload it in the next days.

**Comment by kbitson** [comment]
I had the same issue as OP but solved it. I uninstalled spotify-ripper and 2.7.10, installed 3.5.1, set 3.5.1 to local and global, then reinstalled spotify-ripper. 

These are the exact steps I took. Though some of these are redundant and not necessary, I figured it would be best to include them just in case something stupid on my part happened to be the fix. I will try some testing after I've finished using spotty ripper for the night. 

`pip uninstall spotify-ripper`
`pip install --upgrade pip`
`pyenv uninstall 2.7.10`
`export CONFIGURE_OPTS="--enable-unicode=ucs4"`
`pyenv install 3.5.1`
`pyenv local 3.5.1`
`pyenv global 3.5.1`
`pip install --upgrade pip`
`pip install spotify-ripper`

**Comment by hover20** [comment]
Yeah!

Your solution works great! Thanks a lot!

Currently I'm creating an extended vagrantfile. I will include your solution :)

**Comment by kbitson** [comment]
Thanks for checking! I did some quick testing and it looks like 2.7.10 and 2.7.11 are effecting this issue. spotify-ripper worked with 3.5.1 and 2.7.9, but not 2.7.10 or 2.7.11

###  Solution
`pip uninstall spotify-ripper`
`pyenv install 3.5.1`
`pyenv local 3.5.1`
`pyenv global 3.5.1`
`pip install spotify-ripper`

I did not need to remove 2.7.10 or .11, just simply added 2.7.9 or 3.5.1 (and most likely others that work too, but I did not test)

**Comment by jstiers** [comment]
Love you guys <3
