### ISSUE TITLE
error in ripping playlist

### ISSUE THREAD

**Issue by nimmuk09** [jrnewell/spotify-ripper#219]
Hi, after updating my arch box, I have a problem in ripping playlist.  Ripping a song is ok.
Here's my error. 
`Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 227, in run
    audio_file = self.format_track_path(idx, track)
  File "/usr/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 585, in format_track_path
    format_track_string(self, args.format[0].strip(), idx, track)
  File "/usr/lib/python2.7/site-packages/spotify_ripper/utils.py", line 175, in format_track_string
    album_browser.load()
  File "/usr/lib/python2.7/site-packages/spotify/album.py", line 264, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/spotify/utils.py", line 242, in load
    _check_error(obj)
  File "/usr/lib/python2.7/site-packages/spotify/utils.py", line 206, in _check_error
    error_type, ignores=[spotify.ErrorType.IS_LOADING])
  File "/usr/lib/python2.7/site-packages/spotify/error.py", line 31, in maybe_raise
    raise LibError(error_type)
LibError: General permanent error
`
It seems it is a problem with pythong libraries.  I think it is the opposite of [#176](https://github.com/jrnewell/spotify-ripper/issues/176).

**Comment by asoretmadolell** [comment]
Friend, I've had de same problem right now but I tried again just once afterwards and it was working fine. It wasn't after updating anything, so I'm guessing it was an error from the server?

**Comment by micant** [comment]
+1 , I had the same issue, after reinstalling everything from python up, the problem persisted, then randomly went away. I believe it's a timeout issue stemming from the server.

**Comment by vikbez** [comment]
I also experience this issue, but it does not go away for me :(

**Comment by asoretmadolell** [comment]
Could it be solved by just waiting a little longer? How difficult would it be to implement an option to increase the 10 second timeout?

**Comment by LockeFromTheBlock** [comment]
+1

**Comment by vikbez** [comment]
I fixed it for me with https://github.com/jrnewell/spotify-ripper/pull/225/files

**Comment by micant** [comment]
Great suggestion @vikbez, that fixed the issue for me as well

**Comment by jrnewell** [comment]
Ok... I merged that PR into ``2.9.0``.  Let me know if that helps.
