### ISSUE TITLE
Aborting after error occurred or input requested causes crash

### ISSUE THREAD

**Issue by dylanjboyd** [jrnewell/spotify-ripper#22]
Issuing `Ctrl + C` when:
1. `spotify-ripper` has crashed and is stuck at the stack trace
2. Input has been requested by `spotify-ripper` (as shown in the example below)

causes `abort()` to be called on the ripper. This can cause a crash if the ripper had not loaded any files to rip by that point, thus invalidating the need for calling `abort()`.

```
Logging in...
Password: 
Searching for query: temp.txt
Results
Pick track(s) (ex 1-3,5): ^C
Aborting...
Traceback (most recent call last):
  File "/usr/local/bin/spotify-ripper", line 9, in <module>
    load_entry_point('spotify-ripper==1.2.0', 'console_scripts', 'spotify-ripper')()
  File "/usr/local/bin/main.py", line 140, in main
    ripper.abort()
  File "/Library/Python/2.7/site-packages/spotify_ripper/ripper.py", line 375, in abort
    self.clean_up_partial()
  File "/Library/Python/2.7/site-packages/spotify_ripper/ripper.py", line 255, in clean_up_partial
    if os.path.exists(self.mp3_file):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

It may be worth checking that a 'cleanup' needs to be called before doing so.

**Comment by jrnewell** [comment]
I committed a fix for this in 2b391c6 / version ```1.2.1``.
