### ISSUE TITLE
Unhashable type: 'LibError', Segmentation Fault

### ISSUE THREAD

**Issue by Rostgnom** [jrnewell/spotify-ripper#228]
First off, great work on that piece of software! Was searching for something to download tracks in 320kbit/s for a long time.

Now to my problem:
A couple of days ago everything worked fine with downloading a playlist of mine. Now, i get the following error:

```
[...]
Logging in...
Logged in as 1148163185
Loading playlist...
Unhandled exception in thread started by <bound method Thread._bootstrap of <Ripper(Thread-1, started 140341375383296)>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.5/threading.py", line 924, in _bootstrap_inner
    (self.name, _format_exc()), file=self._stderr)
  File "/usr/lib/python3.5/traceback.py", line 163, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib/python3.5/traceback.py", line 117, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/usr/lib/python3.5/traceback.py", line 439, in __init__
    _seen.add(exc_value)
TypeError: unhashable type: 'LibError'
Segmentation fault (core dumped)
```

I'd appreciate any hint to what to problem might be.

**Comment by jrnewell** [comment]
I will try my best to replicate, but these type of errors are so hard to debug 😄
