### ISSUE TITLE
Blank lines in input URI file causes crash

### ISSUE THREAD

**Issue by dylanjboyd** [jrnewell/spotify-ripper#23]
Crash occurs when supplying the path to a text file that:
1. contains only one blank line
2. contains a URI preceded by a blank line
3. contains a URI succeeded by a blank line

This is illustrated in the following example. This is seen for cases one and two; in case three, `Loading ### browser...` is also seen after the `Password:` prompt (depending on the URI type).

```
Logging in...
Password: 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Python/2.7/site-packages/spotify_ripper/ripper.py", line 106, in run
    tracks = itertools.chain(*[self.load_link(line.strip()) for line in open(args.uri)])
  File "/Library/Python/2.7/site-packages/spotify_ripper/ripper.py", line 184, in load_link
    link = self.session.get_link(uri)
  File "/Library/Python/2.7/site-packages/spotify/session.py", line 375, in get_link
    return spotify.Link(self, uri=uri)
  File "/Library/Python/2.7/site-packages/spotify/link.py", line 60, in __init__
    assert uri or sp_link, 'uri or sp_link is required'
AssertionError: uri or sp_link is required
```

Ideally, invalid lines should be ignored, thus preventing a crash.

**Comment by jrnewell** [comment]
I committed a fix for this in 45bf85b / version ```1.2.1``.
