### ISSUE TITLE
UnicodeEncodeError in Success Summary

### ISSUE THREAD

**Issue by LockeFromTheBlock** [jrnewell/spotify-ripper#230]
Success Summary (...)
...
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 356, in run
    self.post.print_summary()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/post_actions.py", line 81, in print_summary
    log_tracks(self.success_tracks)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/post_actions.py", line 70, in log_tracks
    track.name)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/post_actions.py", line 59, in print_with_bullet
    print(" * " + _str)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 55: ordinal not in range(128)

**Comment by jrnewell** [comment]
Do any of the suggestions in https://github.com/jrnewell/spotify-ripper/wiki/Help#unicodeencodeerror help?
