### ISSUE TITLE
--play-token-resume TypeError

### ISSUE THREAD

**Issue by Sepsis00** [jrnewell/spotify-ripper#231]
With argument
 --play-token-resume 1h30m
following error:

Spotify Ripper - v2.9.0
  Encoding output:      MP3, VBR 0
  Spotify bitrate:      320 kbps
Traceback (most recent call last):
  File "/usr/local/bin/spotify-ripper", line 9, in <module>
    load_entry_point('spotify-ripper==2.9.0', 'console_scripts', 'spotify-ripper')()
  File "/usr/local/bin/main.py", line 492, in main
    parse_time_str(args.play_token_resume) is None:
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/utils.py", line 128, in parse_time_str
    if re.match(r"^\d{2}:\d{2}$", time_str):
  File "/usr/lib/python2.7/re.py", line 141, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer

**Comment by jrnewell** [comment]
whoops try ``v2.9.1`` 😄

**Comment by Sepsis00** [comment]
fixed! thank you! :blush:👍
