### ISSUE TITLE
Raspberry Pi 2 / ARMv7 - Shared Object File

### ISSUE THREAD

**Issue by RowanKaag** [jrnewell/spotify-ripper#239]
I have problems getting spotify-ripper to work on Raspberry Pi 2, ARMv7

The installation procedure is listed below.

$ curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
.# restart terminal #.
$ pyenv install 2.7.10
$ pyenv global 2.7.10
$ python -V
    ```Python 2.7.10```

$ sudo apt-get install lame build-essential libffi-dev
$ wget https://developer.spotify.com/download/libspotify/libspotify-12.1.51-Linux-armv7-release.tar.gz
$ tar xvf libspotify-12.1.51-Linux-armv7-release.tar.gz
$ cd libspotify-12.1.51-Linux-armv7-release
$ sudo make install prefix=/usr/local
$ pip install spotify-ripper
$ pyenv rehash
$ spotify-ripper

```
Traceback (most recent call last):
  File "/home/osmc/.pyenv/versions/2.7.10/bin/spotify-ripper", line 9, in <module>
    load_entry_point('spotify-ripper==2.9.1', 'console_scripts', 'spotify-ripper')()
  File "/home/osmc/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/osmc/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "/home/osmc/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2345, in load
    return self.resolve()
  File "/home/osmc/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/osmc/.pyenv/versions/2.7.10/bin/main.py", line 7, in <module>
    from spotify_ripper.ripper import Ripper
  File "/home/osmc/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 9, in <module>
    from spotify_ripper.progress import Progress
  File "/home/osmc/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/progress.py", line 11, in <module>
    import spotify
  File "/home/osmc/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify/__init__.py", line 81, in <module>
    from spotify._spotify import ffi, lib  # noqa
ImportError: libspotify.so.12: cannot open shared object file: No such file or directory
```

in ~/.zshrc:
```
export PATH="/home/osmc/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

$ which spotify-ripper
```
/home/osmc/.pyenv/shims/spotify-ripper
```

**Comment by RowanKaag** [comment]
fixed by installing eabi-armv6hf instead

https://developer.spotify.com/download/libspotify/libspotify-12.1.103-Linux-armv6-bcm2708hardfp-release.tar.gz

**Comment by jrnewell** [comment]
I am glad you found the answer :)
