### ISSUE TITLE
Invalid characters in track name?

### ISSUE THREAD

**Issue by dylanjboyd** [jrnewell/spotify-ripper#25]
When trying to rip `spotify:track:3jIdeiONWjY0pr7FoEyRDH`, I receive the following:

```
Loading track...
Ripping spotify:track:3jIdeiONWjY0pr7FoEyRDH
/home/user123456/spotify/classical/City of Birmingham Symphony Orchestra & Birgit Remmert & Sir Simon Rattle & Ladies of the City of Birmingham Symphony Chorus & City of Birmingham Symphony Chorus - Symphony No 3 in D Minor Sehr langsam. 
Misterioso. Durchauss ppp 'O Mensch! Gib acht!' (Nietzsche).mp3
Can't init outfile '/home/user123456/spotify/classical/City of Birmingham Symphony Orchestra & Birgit Remmert & Sir Simon Rattle & Ladies of the City of Birmingham Symphony Chorus & City of Birmingham Symphony Chorus - Symphony No 3 in D 
Minor Sehr langsam. Misterioso. Durchauss ppp 'O Mensch! Gib acht!' (Nietzsche).mp3'
Progress: [                                        ] 0:00 / 9:20From cffi callback <function music_delivery at 0x7f9e088e1de8>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spotify/session.py", line 989, in music_delivery
    spotify._session_instance, audio_format, frames_bytes, num_frames)
  File "/usr/local/lib/python2.7/dist-packages/spotify/utils.py", line 108, in call
    return listener.callback(*args)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 260, in on_music_delivery
    self.rip(session, audio_format, frame_bytes, num_frames)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 369, in rip
    self.pipe.write(frame_bytes);
IOError: (32, 'Broken pipe')
```

I presume this is a result of the characters `!` and/or `'` being a part of the filename, though I'm not entirely sure. This occurs while running Ubuntu Server 14.04 LTS x86_64, so filename length shouldn't be a problem here. Trying to create a file via the bash prompt on Mac OS X Yosemite given that exact filename enclosed in single quotes results in the following:

```
$ touch 'City of Birmingham Symphony Orchestra & Birgit Remmert & Sir Simon Rattle & Ladies of the City of Birmingham Symphony Chorus & City of Birmingham Symphony Chorus - Symphony No 3 in D Minor Sehr langsam. Misterioso. Durchauss ppp 'O Mensch! Gib acht!' (Nietzsche).mp3'
-bash: !': event not found
```

However, this looks like the first `'` is causing the `!` to be evaluated, as opposed to being taken literally.

**Comment by jrnewell** [comment]
Is this related to issue #20?  When I tested on OS X, it failed before my fix for that issue and now it is fine (even with the ```'``` and ```!```)

**Comment by dylanjboyd** [comment]
Ubuntu Server and Mac OS X Yosemite now creates a 521-byte file instead of crashing.

```
user123456@ubuntu:~$ spotify-ripper -l -f -d ~/spotify/classical spotify:track:3jIdeiONWjY0pr7FoEyRDH
Logging in...
Logged in as user123456
Loading track...
Ripping spotify:track:3jIdeiONWjY0pr7FoEyRDH
/home/user123456/spotify/classical/City of Birmingham Symphony Orchestra & Birgit Remmert & Sir Simon Rattle & Ladies of the City of Birmingham Symphony Chorus & City of Birmingham Symphony Chorus - Symphony No 3 in D Minor Sehr langsam. Misterioso. Durchauss ppp 'O Mensch! Gib acht!'.mp3

Rip complete
City of Birmingham Symphony Orchestra & Birgit Remmert & Sir Simon Rattle & Ladies of the City of Birmingham Symphony Chorus & City of Birmingham Symphony Chorus - Symphony No 3 in D Minor Sehr langsam. Misterioso. Durchauss ppp 'O Mensch! Gib acht!'.mp3  [ 521.00 Bytes ]
-------------------------------------------------------------------------------
Setting artist: City of Birmingham Symphony Orchestra/Birgit Remmert/Sir Simon Rattle/Ladies of the City of Birmingham Symphony Chorus/City of Birmingham Symphony Chorus
Setting album: Mahler: Symphony No. 3
Setting title: Symphony No 3 in D Minor: Sehr langsam. Misterioso. Durchauss ppp 'O Mensch! Gib acht!' (Nietzsche)
Setting track info: (1, 11)
Setting disc info: (2, 2)
Setting release year: 1998
Adding image cover.jpg
Time: 00:00     MPEG1, Layer III        [ ~159 kb/s @ 44100 Hz - Joint Stereo ]
-------------------------------------------------------------------------------
ID3 v2.4: 7 frames
Writing ID3 version v2.4
-------------------------------------------------------------------------------
Logging out...
```

**Comment by dylanjboyd** [comment]
This doesn't seem to be just for that playlist or track - everything I pass in is now ripping immediately as a 521-byte file:

```
Loading track...
Ripping spotify:track:6dCDJsHAAFby1DclZvdwdI
/home/user123456/spotify/classical/William Walton - Concerto for Violin & Orchestra 1. Andante tranquilo.mp3

Rip complete
William Walton - Concerto for Violin & Orchestra 1. Andante tranquilo.mp3       [ 521.00 Bytes ]
-------------------------------------------------------------------------------
Setting artist: William Walton
Setting album: Walton: Symphonies 1 & 2; Violin Concerto; Viola Concerto; Cello Concerto
Setting title: Concerto for Violin & Orchestra: 1. Andante tranquilo
Setting track info: (1, 9)
Setting disc info: (2, 2)
Setting release year: 2012
Adding image cover.jpg
Time: 00:00     MPEG1, Layer III        [ ~159 kb/s @ 44100 Hz - Joint Stereo ]
-------------------------------------------------------------------------------
ID3 v2.4: 7 frames
Writing ID3 version v2.4
-------------------------------------------------------------------------------
Loading track...
Ripping spotify:track:1JlTNz0NIJhrhGy46GXzpR
/home/user123456/spotify/classical/William Walton - Concerto for Violin & Orchestra 2. Presto capriccioso alla napolitana.mp3

Rip complete
William Walton - Concerto for Violin & Orchestra 2. Presto capriccioso alla napolitana.mp3      [ 521.00 Bytes ]
-------------------------------------------------------------------------------
Setting artist: William Walton
Setting album: Walton: Symphonies 1 & 2; Violin Concerto; Viola Concerto; Cello Concerto
Setting title: Concerto for Violin & Orchestra: 2. Presto capriccioso alla napolitana
Setting track info: (2, 9)
Setting disc info: (2, 2)
Setting release year: 2012
Adding image cover.jpg
Time: 00:00     MPEG1, Layer III        [ ~159 kb/s @ 44100 Hz - Joint Stereo ]
-------------------------------------------------------------------------------
ID3 v2.4: 7 frames
Writing ID3 version v2.4
-------------------------------------------------------------------------------
Loading track...
Ripping spotify:track:5ttRNcAn8WkT92XPVuJFwo
/home/user123456/spotify/classical/William Walton - Concerto for Violin & Orchestra 3. Vivace.mp3

Rip complete
William Walton - Concerto for Violin & Orchestra 3. Vivace.mp3  [ 521.00 Bytes ]
-------------------------------------------------------------------------------
Setting artist: William Walton
Setting album: Walton: Symphonies 1 & 2; Violin Concerto; Viola Concerto; Cello Concerto
Setting title: Concerto for Violin & Orchestra: 3. Vivace
Setting track info: (3, 9)
Setting disc info: (2, 2)
Setting release year: 2012
Adding image cover.jpg
Time: 00:00     MPEG1, Layer III        [ ~159 kb/s @ 44100 Hz - Joint Stereo ]
-------------------------------------------------------------------------------
ID3 v2.4: 7 frames
Writing ID3 version v2.4
-------------------------------------------------------------------------------
Loading track...
Ripping spotify:track:4YzWhZQScJM6jr2tTvYHeS
/home/user123456/spotify/classical/Murray Perahia - Rondo in A Major for Piano and Orchestra, K.386.mp3

Rip complete
Murray Perahia - Rondo in A Major for Piano and Orchestra, K.386.mp3    [ 521.00 Bytes ]
-------------------------------------------------------------------------------
Setting artist: Murray Perahia
Setting album: Mozart: Piano Concertos No. 21 in C Major K.467 & No. 23 in A Major K.488 - Sony Classical Masters
Setting title: Rondo in A Major for Piano and Orchestra, K.386
Setting track info: (8, 0)
Setting disc info: (1, 1)
Setting release year: 1984
Adding image cover.jpg
Time: 00:00     MPEG1, Layer III        [ ~159 kb/s @ 44100 Hz - Joint Stereo ]
-------------------------------------------------------------------------------
ID3 v2.4: 7 frames
Writing ID3 version v2.4
-------------------------------------------------------------------------------
Loading track...
Ripping spotify:track:2MklGAmYEoQ1gkHVpH4IkM
/home/user123456/spotify/classical/Claudio Abbado - Burleske for Piano and Orchestra in D Minor.mp3

Rip complete
Claudio Abbado - Burleske for Piano and Orchestra in D Minor.mp3        [ 521.00 Bytes ]
-------------------------------------------------------------------------------
Setting artist: Claudio Abbado
Setting album: Richard Strauss: Orchestral Works and Concertos
Setting title: Burleske for Piano and Orchestra in D Minor
Setting track info: (15, 0)
Setting disc info: (4, 7)
Setting release year: 2014
Adding image cover.jpg
Time: 00:00     MPEG1, Layer III        [ ~159 kb/s @ 44100 Hz - Joint Stereo ]
-------------------------------------------------------------------------------
ID3 v2.4: 7 frames
Writing ID3 version v2.4
-------------------------------------------------------------------------------
Loading track...
Ripping spotify:track:0khJ40OuZxPzLgLVC3bKZY
/home/user123456/spotify/classical/Richard Strauss - Tod und Verklärung, Op.24.mp3

Rip complete
Richard Strauss - Tod und Verklärung, Op.24.mp3 [ 521.00 Bytes ]
-------------------------------------------------------------------------------
Setting artist: Richard Strauss
Setting album: Strauss, R.: Tod und Verklärung; Metamorphosen; Four Last Songs
Setting title: Tod und Verklärung, Op.24
Setting track info: (1, 6)
Setting disc info: (1, 1)
Setting release year: 1995
Adding image cover.jpg
Time: 00:00     MPEG1, Layer III        [ ~159 kb/s @ 44100 Hz - Joint Stereo ]
-------------------------------------------------------------------------------
ID3 v2.4: 7 frames
Writing ID3 version v2.4
-------------------------------------------------------------------------------
Loading track...
Ripping spotify:track:6r7vLiPmEYg8ig4UIxglxk
/home/user123456/spotify/classical/Witold Lutosławski - Concerto for Orchestra I. Intrada Allegro maestoso.mp3

Rip complete
```

**Comment by jrnewell** [comment]
Sorry about that.  I didn't realize that it uploads my workspace to pypi index instead of the tagged version of the github repo.  I made a new version ``1.2.2`` that is clean and doesn't exit immediately.
