### ISSUE TITLE
Retrieve large cover

### ISSUE THREAD

**Issue by UsernameIsAndre** [jrnewell/spotify-ripper#262]
Hi,
Thanks for your app.
I notice the current image size is 300x300.
I know it's possible to get 640x640.
Could it be possible to retrieve a large cover and embed it, perhaps as an option?
Thanks!

**Comment by master131** [comment]
I second this. Most of the album covers that get embedded are 300x300 but Spotify does expose higher quality versions through their Web API (640x640).

https://api.spotify.com/v1/tracks/52xaypL0Kjzk0ngwv3oBPR

**Comment by calixto111** [comment]
hi , 
what is the Command Line ?
--large-cover-art  is not working  
thanks

**Comment by master131** [comment]
@calixto111 Make sure you're using the latest committed version. The package on hasn't been updated on pypi.

`sudo pip install git+git://github.com/jrnewell/spotify-ripper.git`

**Comment by calixto111** [comment]
Thank you very much , working now

**Comment by jrnewell** [comment]
sorry, forgot to make a new version.  I just made a new one that has it - 2.10.4

**Comment by calixto111** [comment]
Hi, 
I have notice that if it doesn't find the large cover art , it does not get any .
Can you make it get the 300 X 300 if it does not find the large one?

Thanks

**Comment by calixto111** [comment]
hi,
large cover is working fine with flac , but when it does not find the large cover the default does this ....

Spotify error detected
must be convertible to a buffer, not Image
Traceback (most recent call last):
File "/Users/Panchovilla/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 334, in run
set_metadata_tags(args, self.audio_file, idx, track, self)
File "/Users/Panchovilla/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/tags.py", line 348, in set_metadata_tags
set_vorbis_comments(audio)
File "/Users/Panchovilla/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/tags.py", line 257, in set_vorbis_comments
save_cover_image(embed_image)
File "/Users/Panchovilla/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/tags.py", line 109, in save_cover_image
write_image(args.cover_file_and_embed)
File "/Users/Panchovilla/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/tags.py", line 104, in write_image
f.write(data)
TypeError: must be convertible to a buffer, not Image
Skipping to next track...
Deleting partially ripped file

Could you please check ?
try with this album
https://open.spotify.com/album/3dP4oUnBVhc8od7R9PbqHk

thank you in advance

**Comment by jrnewell** [comment]
ok i think i fixed the "using the smaller cover as a backup" issue in ``2.10.5``.
