### ISSUE TITLE
Getting an error when trying to run the app and don't konw what it is?...

### ISSUE THREAD

**Issue by sgarratt77** [jrnewell/spotify-ripper#272]
I'm not sure what or why this is as I am not really any kind of programmer. Please help me. I am getting the following:

"
sudo spotify-ripper -u xxxxxxxx list_of_uris.txt
Spotify Ripper - v2.10.4
  Encoding output:	MP3, VBR 0
  Spotify bitrate:	160 kbps
  Unicode support:	Yes
  Output directory:	/Volumes/HyBrid HDD/Recording Songs/Music
  Settings directory:	/Volumes/HyBrid HDD/Users/Steve/.spotify-ripper
  Format String:	{playlist}/{album_artist}/{artist}/{album}/{track_idx:3} - {track_name}.{ext}
  Overwrite files:	No
Logging in...
Logged in as xxxxxxxxx
Loading playlist...

Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 233, in run
    audio_file = self.format_track_path(idx, track)
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 609, in format_track_path
    track.load()
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify/track.py", line 81, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify/utils.py", line 246, in load
    raise spotify.Timeout(timeout)
Timeout: Operation did not complete in 10.000s
"

my user config looks like this:

[main]
user = xxx
password = xxx
format = {playlist}/{album_artist}/{artist}/{album}/{track_idx:3} - {track_name}.{ext}
format-case = capitalize
quality = 160
bitrate = 128
playlist-sync = True
playlist-m3u = True
playlist-wpl = True
remove-offline-cache = True
normalize = True
windows-safe = True
;ascii = True

anyone got any ideas?

**Comment by bleedr** [comment]
Having since today exactly the same issue, using:
spotify-ripper -c -uXXXX --flat spotify:user:XXXX

**Comment by sgarratt77** [comment]
i tried it with the following variations (trying taking out any mention of URI in txt file, just quoting file and not the path to it since I had already cd'd to the folder, etc):

"sudo spotify-ripper -u xxx /Volumes/HyBrid\ HDD/Recording\ Songs/Music/DLlist.txt"

and got:

Spotify Ripper - v2.10.4
  Encoding output:	MP3, VBR 0
  Spotify bitrate:	160 kbps
  Unicode support:	Yes
  Output directory:	/Volumes/HyBrid HDD/Recording Songs/Music
  Settings directory:	/Volumes/HyBrid HDD/Users/Steve/.spotify-ripper
  Format String:	{playlist}/{album_artist}/{artist}/{album}/{track_idx:3} - {track_name}.{ext}
  Overwrite files:	No
Logging in...
Logged in as xxx
Loading album browser...
Loading playlist...
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/Users/xxx/.pyenv/versions/2.7.12/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/xxx/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 233, in run
    audio_file = self.format_track_path(idx, track)
  File "/Users/xxx/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 609, in format_track_path
    track.load()
  File "/Users/xxx/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify/track.py", line 81, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/Users/xxx/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify/utils.py", line 246, in load
    raise spotify.Timeout(timeout)
Timeout: Operation did not complete in 10.000s



trying "sudo spotify-ripper -u xxx uri /Volumes/HyBrid\ HDD/Recording\ Songs/Music/DLlist.txt"

gave:

Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 224, in run
    tracks = list(get_tracks_from_uri(uri))
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 219, in get_tracks_from_uri
    return self.load_link(uri)
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 416, in load_link
    link = self.session.get_link(uri)
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify/session.py", line 376, in get_link
    return spotify.Link(self, uri=uri)
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify/link.py", line 73, in __init__
    'Failed to get link from Spotify URI: %r' % uri)
ValueError: Failed to get link from Spotify URI: 'uri'



and

"sudo spotify-ripper -u xxx uri DLlist.txt"

gave:

Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 224, in run
    tracks = list(get_tracks_from_uri(uri))
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 219, in get_tracks_from_uri
    return self.load_link(uri)
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 416, in load_link
    link = self.session.get_link(uri)
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify/session.py", line 376, in get_link
    return spotify.Link(self, uri=uri)
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify/link.py", line 73, in __init__
    'Failed to get link from Spotify URI: %r' % uri)
ValueError: Failed to get link from Spotify URI: 'uri'


trying "sudo spotify-ripper -u xxx uri list_of_uris.txt"

gave:

Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 224, in run
    tracks = list(get_tracks_from_uri(uri))
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 219, in get_tracks_from_uri
    return self.load_link(uri)
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 416, in load_link
    link = self.session.get_link(uri)
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify/session.py", line 376, in get_link
    return spotify.Link(self, uri=uri)
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify/link.py", line 73, in __init__
    'Failed to get link from Spotify URI: %r' % uri)
ValueError: Failed to get link from Spotify URI: 'uri'


trying "sudo spotify-ripper -u xxx DL.txt"

gave:

Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 233, in run
    audio_file = self.format_track_path(idx, track)
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 609, in format_track_path
    track.load()
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify/track.py", line 81, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/Users/Steve/.pyenv/versions/2.7.12/lib/python2.7/site-packages/spotify/utils.py", line 246, in load
    raise spotify.Timeout(timeout)
Timeout: Operation did not complete in 10.000s




I am completely stumped. I thought I saw a comment about not typing 'URI' because it confused the app but trying without seems not to make a difference.

can anyone help please?

**Comment by jrnewell** [comment]
I don't think you are doing anything incorrectly, I added a ``--timeout`` option if you want to increase the timeout value and wait longer.  However, libspotify failing to loading links has been issue since I started this.  The bad news is that I don't think there is much that can fix it since libspotify is deprecated, but sometimes it just automatically resolves itself.
