### ISSUE TITLE
Expected string or buffer

### ISSUE THREAD

**Issue by orcomma** [jrnewell/spotify-ripper#273]
Hi

I'm getting this error:

```
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 232, in run
    audio_file = self.format_track_path(idx, track)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 612, in format_track_path
    format_track_string(self, args.format.strip(), idx, track)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/utils.py", line 184, in format_track_string
    escape_filename_part(track.artists[0].name))
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/utils.py", line 60, in escape_filename_part
    part = re.sub(r"\s*/\s*", r' & ', part)
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```

Any ideas what could be wrong?

Windows 10 Anniversary Ubuntu Bash, fully updated/upgraded. I'm a novice with Linux but a pro with Windows :(

**Comment by jrnewell** [comment]
I haven't tried yet, but I just updated my windows partition to the anniversary edition, so I will test it out soon.

**Comment by orcomma** [comment]
Thanks!! Great application btw!

**Comment by Joniator** [comment]
Pushing this, still existing with [this Playlist](https://open.spotify.com/user/1156104533/playlist/7ym4bhhQlQPer5N2HqOF86) 

```
Loading playlist...

Exception in thread SpotifyRipperThread:

Traceback (most recent call last):

  File "/home/osmc/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()

  File "/home/osmc/src/spotify-ripper/spotify_ripper/ripper.py", line 233, in run
    audio_file = self.format_track_path(idx, track)

  File "/home/osmc/src/spotify-ripper/spotify_ripper/ripper.py", line 615, in format_track_path
    format_track_string(self, args.format.strip(), idx, track)

  File "/home/osmc/src/spotify-ripper/spotify_ripper/utils.py", line 184, in format_track_string
    escape_filename_part(track.artists[0].name))

  File "/home/osmc/src/spotify-ripper/spotify_ripper/utils.py", line 60, in escape_filename_part
    part = re.sub(r"\s*/\s*", r' & ', part)

  File "/home/osmc/.pyenv/versions/2.7.10/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)

TypeError: expected string or buffer`
```
