### ISSUE TITLE
Image not found when ripping track

### ISSUE THREAD

**Issue by dylanjboyd** [jrnewell/spotify-ripper#40]
I received the following error when trying to rip track `spotify:track:1S2fiTIYw8cy2lH3JBXN64`
```
Loading track...
[ 11 / 1844 ] Ripping spotify:track:1S2fiTIYw8cy2lH3JBXN64
/Users/user/Downloads/spotify/Janelle Monáe/The Electric Lady/Janelle Monáe - Givin Em What They Love [feat. Prince].mp3
Progress: [======================================= ] 04:24 / 04:26	(~00m 00s remaining)
Total:    [                                        ] 04:24 / 11:04:53	(~06h 55m remaining)
Rip complete
Warning: exception while saving id3 tag: <class 'mutagen.id3._util.error'>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Python/2.7/site-packages/spotify_ripper/ripper.py", line 159, in run
    set_id3_and_cover(args, self.mp3_file, track)
  File "/Library/Python/2.7/site-packages/spotify_ripper/id3.py", line 138, in set_id3_and_cover
    if image is not None: rm_file("cover.jpg")
UnboundLocalError: local variable 'image' referenced before assignment
```
*Mac OS X 10.10.3*
*spotify-ripper 1.3.1*

**Comment by dylanjboyd** [comment]
I ran the same process again, and the error didn't seem to reproduce itself. Would you perhaps have an idea as to what caused this?

**Comment by dylanjboyd** [comment]
Additionally, I've come across the following error. Both of these errors only seem to happen when I do something similar to window switching, and an activity similar to web browsing in the foreground.
```
Loading track...
[ 57 / 133 ] Ripping spotify:track:1zkEpVfEA6aqiCOiollL8j
/Users/user/Downloads/spotify/ukf/Tokyo Prose Feat. Riya/UKF Drum & Bass 2014/Tokyo Prose Feat. Riya - Waiting On.mp3
Progress: [======================================= ] 05:16 / 05:19	(~00m 00s remaining)
Total:    [=================                       ] 04:48:11 / 10:56:46	(~04h 16m remaining)
Rip complete
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Python/2.7/site-packages/spotify_ripper/ripper.py", line 159, in run
    set_id3_and_cover(args, self.mp3_file, track)
  File "/Library/Python/2.7/site-packages/spotify_ripper/id3.py", line 64, in set_id3_and_cover
    fh_cover = open('cover.jpg', 'wb')
IOError: [Errno 2] No such file or directory: u'cover.jpg'
```
*Mac OS X 10.10.3*
*spotify-ripper 1.3.1*

**Comment by jrnewell** [comment]
While I was looking at this, I realized I didn't really need to be saving the cover image to a temp file anymore since I am using Mutagen.  I just pass the byte string directly to the library, so I think that will solve issuing revolving around dealing with the ``cover.jpg`` file - the change is in version ``1.4.0``.

For whatever reason, in your first issue mutagen didn't save the id3 tag properly and caused an exception.  Not sure what that was about.
