### ISSUE TITLE
not working version 2.0.2

### ISSUE THREAD

**Issue by skypce** [jrnewell/spotify-ripper#51]
Spotify Ripper - v2.0.2
  Encoding output:	MP3, VBR 0
  Spotify bitrate:	320 kbps
  Unicode support:	Yes
  Output directory:	/home/shezar/d
  Settings directory:	/home/shezar/.spotify-ripper
  Export Organization:	Single directory (with playlist index)
  Overwrite files:	No
Logging in...
Password: 
Logged in as skypce2015
Loading album browser...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/shezar/.local/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 139, in run
    self.progress.calc_total(tracks)
  File "/home/shezar/.local/lib/python2.7/site-packages/spotify_ripper/progress.py", line 61, in calc_total
    audio_file = self.ripper.track_path(idx, track)
  File "/home/shezar/.local/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 389, in track_path
    file_name = truncate(filled_idx + " - " + artist + " - " + track_name, 251) + extension
NameError: global name 'artist' is not defined

thank you in advance.

**Comment by jrnewell** [comment]
Sorry about that.  Fixed in version ``2.0.3``.

**Comment by skypce** [comment]
thank you James

2015-06-23 16:19 GMT-03:00 James Newell <notifications@github.com>:
