### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by fratellolupo** [jrnewell/spotify-ripper#54]
Hello,

I have trouble running the application with Python 3 on Debian Jessie.
- 1) issue with ConfigParser

Traceback (most recent call last):
  File "/usr/local/bin/spotify-ripper", line 9, in <module>
    load_entry_point('spotify-ripper==2.0.0', 'console_scripts', 'spotify-ripper')()
  File "/usr/local/lib/python3.4/dist-packages/setuptools-12.4-py3.4.egg/pkg_resources/__init__.py", line 521, in load_entry_point
  File "/usr/local/lib/python3.4/dist-packages/setuptools-12.4-py3.4.egg/pkg_resources/__init__.py", line 2632, in load_entry_point
  File "/usr/local/lib/python3.4/dist-packages/setuptools-12.4-py3.4.egg/pkg_resources/__init__.py", line 2312, in load
  File "/usr/local/lib/python3.4/dist-packages/setuptools-12.4-py3.4.egg/pkg_resources/__init__.py", line 2318, in resolve
  File "/usr/local/bin/main.py", line 4, in <module>
    __import__('pkg_resources').run_script('spotify-ripper==2.0.0', 'main.py')
  File "/usr/local/lib/python3.4/dist-packages/setuptools-12.4-py3.4.egg/pkg_resources/__init__.py", line 698, in run_script
  File "/usr/local/lib/python3.4/dist-packages/setuptools-12.4-py3.4.egg/pkg_resources/__init__.py", line 1616, in run_script
  File "/usr/local/lib/python3.4/dist-packages/spotify_ripper-2.0.0-py3.4.egg/EGG-INFO/scripts/main.py", line 13, in <module>
    import ConfigParser
ImportError: No module named 'ConfigParser

I solved this one by replacing the import in main.py with:
if sys.version_info >= (3, 0):
    import configparser as ConfigParser
else:
    import ConfigParser

2) then I get this other error:
Traceback (most recent call last):
  File "/usr/local/bin/spotify-ripper", line 9, in <module>
    load_entry_point('spotify-ripper==2.0.0', 'console_scripts', 'spotify-ripper')()
  File "/usr/local/lib/python3.4/dist-packages/spotify_ripper-2.0.0-py3.4.egg/EGG-INFO/scripts/main.py", line 287, in main
    ripper.progress.handle_resize()
  File "/usr/local/lib/python3.4/dist-packages/spotify_ripper-2.0.0-py3.4.egg/spotify_ripper/progress.py", line 106, in handle_resize
    h, w = array(h, ioctl(sys.stdout, termios.TIOCGWINSZ, null_str))[:2]
TypeError: must be a unicode character, not bytes

Did I miss something?

**Comment by skypce** [comment]
try to update to version 2.0.3 
sudo pip install --upgrade spotify-ripper

**Comment by fratellolupo** [comment]
Same:
Finished processing dependencies for spotify-ripper==2.0.3
Traceback (most recent call last):
  File "/usr/local/bin/spotify-ripper", line 9, in <module>
    load_entry_point('spotify-ripper==2.0.3', 'console_scripts', 'spotify-ripper')()
  File "/usr/local/lib/python3.4/dist-packages/setuptools-12.4-py3.4.egg/pkg_resources/__init__.py", line 521, in load_entry_point
  File "/usr/local/lib/python3.4/dist-packages/setuptools-12.4-py3.4.egg/pkg_resources/__init__.py", line 2632, in load_entry_point
  File "/usr/local/lib/python3.4/dist-packages/setuptools-12.4-py3.4.egg/pkg_resources/__init__.py", line 2312, in load
  File "/usr/local/lib/python3.4/dist-packages/setuptools-12.4-py3.4.egg/pkg_resources/__init__.py", line 2318, in resolve
  File "/usr/local/bin/main.py", line 4, in <module>
    __import__('pkg_resources').run_script('spotify-ripper==2.0.3', 'main.py')
  File "/usr/local/lib/python3.4/dist-packages/setuptools-12.4-py3.4.egg/pkg_resources/__init__.py", line 698, in run_script
  File "/usr/local/lib/python3.4/dist-packages/setuptools-12.4-py3.4.egg/pkg_resources/__init__.py", line 1616, in run_script
  File "/usr/local/lib/python3.4/dist-packages/spotify_ripper-2.0.3-py3.4.egg/EGG-INFO/scripts/main.py", line 13, in <module>
    import ConfigParser
ImportError: No module named 'ConfigParser'y

**Comment by skypce** [comment]
sudo apt-get install libnss3-tools python3-dev build-essential libffi-dev

So you can try install directly pip from this page:
https://pip.pypa.io/en/stable/installing.html

remember do  a apt-get remove pip before.

2015-06-24 19:49 GMT-03:00 fratellolupo <notifications@github.com>:

**Comment by skypce** [comment]
i have latest version in ubuntu 15.04 running without problems. :P

2015-06-24 20:02 GMT-03:00 skypce <skypce@gmail.com>:

**Comment by skypce** [comment]
sorry for remove pip : sudo apt-get purge python-pip

2015-06-24 20:02 GMT-03:00 skypce <skypce@gmail.com>:

**Comment by jrnewell** [comment]
I am will try to improve Python 3 compatibility in the next days. I was neglecting it lately.

**Comment by fratellolupo** [comment]
Can we be of help?

**Comment by jrnewell** [comment]
Yeah, if you have any suggestions I will try to incorporate them.  I tried updating Python 3 compatibility with version ``2.0.4``.  Can you try and see if it works for you?

**Comment by fratellolupo** [comment]
It just works now; thank you!
