### ISSUE TITLE
cant get playlist - 'Ripper' has no attribute 'track_path'

### ISSUE THREAD

**Issue by faer** [jrnewell/spotify-ripper#58]
Hello.

First of all, cool software, thanks for that.
It works fine when I am looking for one single track.

When I try to rip a playlist, I receive the following output:

Loading playlist...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 139, in run
    self.progress.calc_total(tracks)
  File "/usr/local/lib/python2.7/site-packages/spotify_ripper/progress.py", line 61, in calc_total
    audio_file = self.ripper.track_path(idx, track)
AttributeError: 'Ripper' object has no attribute 'track_path'

Could you help me out?
Thanks!

**Comment by jrnewell** [comment]
Sorry about that - fixed in version ``2.1.1``.

**Comment by faer** [comment]
Thank you very much for the fast patch. Looks like its working fine now! Cheers
