### ISSUE TITLE
error version 2.1.2

### ISSUE THREAD

**Issue by skypce** [jrnewell/spotify-ripper#64]
spotify:user:spotifyenespa%25C3%25B1ol:playlist:5PlaYOSGtktsqP8waCtudY  
Spotify Ripper - v2.1.2
  Encoding output:	MP3, VBR 0
  Spotify bitrate:	320 kbps
  Unicode support:	Yes
  Output directory:	/home/shezar/Music
  Settings directory:	/home/shezar/.spotify-ripper
  Format String:	{album_artist}/{album}/{artist} - {track_name}.{ext}
  Overwrite files:	No
Logging in...
Password: 
Logged in as skypce2015
Loading playlist...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 139, in run
    self.progress.calc_total(tracks)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/progress.py", line 59, in calc_total
    track.load()
  File "/usr/local/lib/python2.7/dist-packages/spotify/track.py", line 80, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/spotify/utils.py", line 240, in load
    raise spotify.Timeout(timeout)
Timeout: Operation did not complete in 10.000s

**Comment by tinstep** [comment]
Affects me too both before upgrade and on 2.1.2.


Spotify Ripper - v2.1.2
  Encoding output:	FLAC, Compression Level: 8
  Spotify bitrate:	320 kbps
  Unicode support:	Yes
  Output directory:	/share/Holding/downloads/_spotify_rips
  Settings directory:	/home/user/.spotify-ripper
  Format String:	{album_artist}/({year}) -  {album}/{track_num} - {track_name}.{ext}
  Overwrite files:	No
Logging in...
Logged in as USER
Loading album browser...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 131, in run
    tracks = self.load_link(uri)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 223, in load_link
    album_browser.load()
  File "/usr/local/lib/python2.7/dist-packages/spotify/album.py", line 262, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/spotify/utils.py", line 240, in load
    raise spotify.Timeout(timeout)
Timeout: Operation did not complete in 10.000s

^C
Aborting...
Logging out...

**Comment by msharris** [comment]
I had the same error this morning. Strangely it doesn't occur on every run.

**Comment by jrnewell** [comment]
I can't really control when it times-out loading a track but I will put in some exception handling so it skips over that failed track instead of just exiting completely.

**Comment by jrnewell** [comment]
The script won't completely exit on a loading error in version ``2.2.0``

**Comment by tinstep** [comment]
Actually, I think this error can be caused server end, I can try ...get the error , then try an hour latter and it works !

Happy for you to close (or increase trapping to identify the error further)
