### ISSUE TITLE
Exception: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by bkk2912** [jrnewell/spotify-ripper#88]
For me the ripper ocassionally runs into exceptions:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 261, in run
    self.print_summary()
  File "/usr/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 159, in print_summary
    log_tracks(self.failure_tracks)
  File "/usr/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 146, in log_tracks
    print(" • " + track.artists[0].name + " - " +
TypeError: coercing to Unicode: need string or buffer, NoneType found

Thanks for the great work so far. It is a really great tool!

**Comment by VikasRana** [comment]
you tried -a in command?

**Comment by bkk2912** [comment]
Thanks a lot for the hint!! Will try it.

**Comment by bkk2912** [comment]
I can confirm this exception is even thrown when using "ascii = True" in config.ini

**Comment by VikasRana** [comment]
don't use config file and put -a in command and then try.

**Comment by jrnewell** [comment]
Do you have a particular track where that is failing?  It sort of looks like ``track.artists[0].name`` is None for that track.  I will try to put in more checks in that function but it will be difficult to test if it solved your issue...

**Comment by bkk2912** [comment]
the if-statements in your update seem to work! Thanks a lot!
