### ISSUE TITLE
Errors when ogg

### ISSUE THREAD

**Issue by TobyMellor** [jrnewell/spotify-ripper#97]
Hi,
After downloading a song in the Vorbis OGG format, I got this error:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 272, in run
    set_metadata_tags(args, self.audio_file, track)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/tags.py", line 295, in set_metadata_tags
    set_vorbis_comments(audio)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/tags.py", line 235, in set_vorbis_comments
    audio.save()
  File "/usr/local/lib/python2.7/dist-packages/mutagen/ogg.py", line 504, in save
    reraise(self._Error, e, sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/mutagen/ogg.py", line 502, in save
    self.tags._inject(fileobj)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/oggvorbis.py", line 117, in _inject
    OggPage.replace(fileobj, old_pages, new_pages)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/ogg.py", line 390, in replace
    cls.renumber(fileobj, serial, sequence)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/ogg.py", line 224, in renumber
    page = OggPage(fileobj)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/ogg.py", line 111, in __init__
    raise error("unable to read full data")
OggVorbisHeaderError: unable to read full data

I saw mutagen, so I tried to upgrade it. Now it's giving me this error when I type "spotify-ripper".

Traceback (most recent call last):
  File "/usr/local/bin/spotify-ripper", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: mutagen==1.29

**Comment by TobyMellor** [comment]
I tried with Python3, this is the error I'm getting now. I'm using the command "spotify-ripper --vorbis -u MYUSERNAME -p MYPASS spotify:track:0C4ejWmOTMv8vuYj85mf8m"

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/mutagen/ogg.py", line 502, in save
    self.tags._inject(fileobj)
  File "/usr/local/lib/python3.4/dist-packages/mutagen/oggvorbis.py", line 117, in _inject
    OggPage.replace(fileobj, old_pages, new_pages)
  File "/usr/local/lib/python3.4/dist-packages/mutagen/ogg.py", line 390, in replace
    cls.renumber(fileobj, serial, sequence)
  File "/usr/local/lib/python3.4/dist-packages/mutagen/ogg.py", line 224, in renumber
    page = OggPage(fileobj)
  File "/usr/local/lib/python3.4/dist-packages/mutagen/ogg.py", line 111, in __init__
    raise error("unable to read full data")
mutagen.ogg.error: unable to read full data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/spotify_ripper/ripper.py", line 272, in run
    set_metadata_tags(args, self.audio_file, track)
  File "/usr/local/lib/python3.4/dist-packages/spotify_ripper/tags.py", line 295, in set_metadata_tags
    set_vorbis_comments(audio)
  File "/usr/local/lib/python3.4/dist-packages/spotify_ripper/tags.py", line 235, in set_vorbis_comments
    audio.save()
  File "/usr/local/lib/python3.4/dist-packages/mutagen/ogg.py", line 504, in save
    reraise(self._Error, e, sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/mutagen/_compat.py", line 81, in reraise
    raise tp(value).with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/mutagen/ogg.py", line 502, in save
    self.tags._inject(fileobj)
  File "/usr/local/lib/python3.4/dist-packages/mutagen/oggvorbis.py", line 117, in _inject
    OggPage.replace(fileobj, old_pages, new_pages)
  File "/usr/local/lib/python3.4/dist-packages/mutagen/ogg.py", line 390, in replace
    cls.renumber(fileobj, serial, sequence)
  File "/usr/local/lib/python3.4/dist-packages/mutagen/ogg.py", line 224, in renumber
    page = OggPage(fileobj)
  File "/usr/local/lib/python3.4/dist-packages/mutagen/ogg.py", line 111, in __init__
    raise error("unable to read full data")
mutagen.oggvorbis.OggVorbisHeaderError: unable to read full data
